/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/main/cart`; params?: Router.UnknownInputParams; } | { pathname: `/main/explore`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/notification`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ProductCardDetails/MeasurementForm`; params?: Router.UnknownInputParams; } | { pathname: `/ProductCardDetails/ProductDetails`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/main/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/main/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/main/notification`; params?: Router.UnknownOutputParams; } | { pathname: `/main/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductCardDetails/MeasurementForm`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductCardDetails/ProductDetails`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/main/cart${`?${string}` | `#${string}` | ''}` | `/main/explore${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/main/notification${`?${string}` | `#${string}` | ''}` | `/main/profile${`?${string}` | `#${string}` | ''}` | `/ProductCardDetails/MeasurementForm${`?${string}` | `#${string}` | ''}` | `/ProductCardDetails/ProductDetails${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/main/cart`; params?: Router.UnknownInputParams; } | { pathname: `/main/explore`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/notification`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ProductCardDetails/MeasurementForm`; params?: Router.UnknownInputParams; } | { pathname: `/ProductCardDetails/ProductDetails`; params?: Router.UnknownInputParams; };
    }
  }
}
